/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:8651ce1d-ec40-46df-a10d-e92b9ff17554",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_oftVwTJeU",
    "aws_user_pools_web_client_id": "7gauvvevjqh6sp2fe38blgv6b5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hym4lpqfi5dcvejhecy6tmf3ae.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
